### ISSUE TITLE
Cannot start donkeycar sim. Exception: Could not connect to server. 

### ISSUE THREAD

**Issue by innovationty** [autorope/donkeycar#1183]
Here is the information for the exception. I tried to follow the video https://www.youtube.com/watch?v=wqQMmHVT8qw, but it didn't work. 
How could I solve the problem? I really appreciate to get answers.

starting DonkeyGym env
Setting default: start_delay 5.0
Setting default: max_cte 8.0
Setting default: cam_resolution (120, 160, 3)
Setting default: log_level 20
Setting default: steer_limit 1.0
Setting default: throttle_min 0.0
Setting default: throttle_max 1.0
donkey subprocess started
INFO:gym_donkeycar.core.client:connecting to 127.0.0.1:9091
Traceback (most recent call last):
  File "/home/polo/projects/gym-donkeycar/gym_donkeycar/core/client.py", line 45, in connect
    self.s.connect((self.host, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/polo/mysim/manage.py", line 1142, in <module>
    drive(cfg, model_path=args['--model'], use_joystick=args['--js'],
  File "/home/polo/mysim/manage.py", line 92, in drive
    add_simulator(V, cfg)
  File "/home/polo/mysim/manage.py", line 765, in add_simulator
    gym = DonkeyGymEnv(cfg.DONKEY_SIM_PATH, host=cfg.SIM_HOST, env_name=cfg.DONKEY_GYM_ENV_NAME, conf=cfg.GYM_CONF,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/polo/miniconda3/envs/donkey/lib/python3.11/site-packages/donkeycar/parts/dgym.py", line 28, in __init__
    self.env = gym.make(env_name, conf=conf)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/polo/miniconda3/envs/donkey/lib/python3.11/site-packages/gym/envs/registration.py", line 676, in make
    return registry.make(id, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/polo/miniconda3/envs/donkey/lib/python3.11/site-packages/gym/envs/registration.py", line 520, in make
    return spec.make(**kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/polo/miniconda3/envs/donkey/lib/python3.11/site-packages/gym/envs/registration.py", line 140, in make
    env = cls(**_kwargs)
          ^^^^^^^^^^^^^^
  File "/home/polo/projects/gym-donkeycar/gym_donkeycar/envs/donkey_env.py", line 179, in __init__
    super().__init__(level="generated_track", *args, **kwargs)
  File "/home/polo/projects/gym-donkeycar/gym_donkeycar/envs/donkey_env.py", line 91, in __init__
    self.viewer = DonkeyUnitySimContoller(conf=conf)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/polo/projects/gym-donkeycar/gym_donkeycar/envs/donkey_sim.py", line 71, in __init__
    self.client = SimClient(self.address, self.handler)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/polo/projects/gym-donkeycar/gym_donkeycar/core/sim_client.py", line 28, in __init__
    super().__init__(*address)
  File "/home/polo/projects/gym-donkeycar/gym_donkeycar/core/client.py", line 37, in __init__
    self.connect()
  File "/home/polo/projects/gym-donkeycar/gym_donkeycar/core/client.py", line 47, in connect
    raise (
Exception: Could not connect to server. Is it running? If you specified 'remote', then you must start it manually.
closing donkey sim subprocess

**Comment by Ali-Younis** [comment]
Do you have the simulator running?
