### ISSUE TITLE
RNN/3D model does not work with tubplot

### ISSUE THREAD

**Issue by mgagvani** [autorope/donkeycar#1185]
Example command:
```bash
donkey tubplot --tub=data/ --model=models/pilot_24-06-10_4.h5 --type=rnn --limit=30000
```
Results in error:
```python
Traceback (most recent call last):
  File "/home/mgagvani/miniconda3/envs/donkey/bin/donkey", line 8, in <module>
    sys.exit(execute_from_command_line())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/f/Projects/TensorKart-master/donkeycar/donkeycar/management/base.py", line 625, in execute_from_command_line
    c.run(args[2:])
  File "/mnt/f/Projects/TensorKart-master/donkeycar/donkeycar/management/base.py", line 522, in run
    self.plot_predictions(cfg, args.tub, args.model, args.limit,
  File "/mnt/f/Projects/TensorKart-master/donkeycar/donkeycar/management/base.py", line 474, in plot_predictions   
    user_angle = tub_record.underlying['user/angle']
                 ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'underlying'
```
Am using **donkey v5.2.dev2**, developer install on WSL, latest commit. This can be reproduced with both the 3D CNN and RNN for arbitrary length values. 

Another minor thing I didn't want to file a whole new issue for, but `donkey models` shows the length value for RNN values but not for 3D CNN: 
```java
4       pilot_24-06-10_4           KerasLSTM-L:6          rnn  data/ 2024-06-10 19:28:59     None    None
5       pilot_24-06-10_5             Keras3D_CNN           3d  data/ 2024-06-10 21:14:06     None    None
```

**Comment by mgagvani** [comment]
Update: same thing happens with the memory model.
