### ISSUE TITLE
Error when running model using python manage.py drive --model

### ISSUE THREAD

**Issue by LuckyYoon** [autorope/donkeycar#1201]
Both my .savemodel and .tflite models don't work, producing separate errors. I've both models were trained using the donkey ui with around ~11000 pictures. The host computer that was used to trained the model is running donkey v5.2 and the raspberry pi 5 on the car is running donkey v5.1

The .saved model produces the following error:
```
(env) donkey@backseat:~/mycar $ python manage.py drive --model ~/mycar/models/pilot_24-10-17_0.savedmodel --myconfig myconfig.py
________             ______                   _________
___  __ \_______________  /___________  __    __  ____/_____ ________
__  / / /  __ \_  __ \_  //_/  _ \_  / / /    _  /    _  __ `/_  ___/
_  /_/ // /_/ /  / / /  ,<  /  __/  /_/ /     / /___  / /_/ /_  /
/_____/ \____//_/ /_//_/|_| \___/_\__, /      \____/  \__,_/ /_/
                                 /____/

using donkey v5.1.0 ...
INFO:donkeycar.config:loading config file: /home/donkey/mycar/config.py
INFO:donkeycar.config:loading personal config over-rides from myconfig.py
INFO:__main__:PID: 2172
cfg.CAMERA_TYPE PICAM
INFO:__main__:cfg.CAMERA_TYPE PICAM
[0:09:21.170190240] [2172]  INFO Camera camera_manager.cpp:325 libcamera v0.3.2+27-7330f29b
[0:09:21.177607207] [2175]  INFO RPI pisp.cpp:695 libpisp version v1.0.7 28196ed6edcf 29-08-2024 (16:33:32)
[0:09:21.187056736] [2175]  INFO RPI pisp.cpp:1154 Registered camera /base/axi/pcie@120000/rp1/i2c@88000/ov5647@36 to CFE device /dev/media0 and ISP device /dev/media2 using PiSP variant BCM2712_C0
[0:09:21.188278462] [2172]  INFO Camera camera_manager.cpp:325 libcamera v0.3.2+27-7330f29b
[0:09:21.195650595] [2178]  INFO RPI pisp.cpp:695 libpisp version v1.0.7 28196ed6edcf 29-08-2024 (16:33:32)
[0:09:21.205536088] [2178]  INFO RPI pisp.cpp:1154 Registered camera /base/axi/pcie@120000/rp1/i2c@88000/ov5647@36 to CFE device /dev/media0 and ISP device /dev/media2 using PiSP variant BCM2712_C0
INFO:picamera2.picamera2:Initialization successful.
INFO:picamera2.picamera2:Camera now open.
INFO:picamera2.picamera2:Camera configuration has been adjusted!
[0:09:21.208895746] [2172]  INFO Camera camera.cpp:1197 configuring streams: (0) 128x120-BGR888 (1) 640x480-GBRG_PISP_COMP1
[0:09:21.209008969] [2178]  INFO RPI pisp.cpp:1450 Sensor: /base/axi/pcie@120000/rp1/i2c@88000/ov5647@36 - Selected sensor format: 640x480-SGBRG10_1X10 - Selected CFE format: 640x480-PC1g
INFO:picamera2.picamera2:Configuration successful!
INFO:picamera2.picamera2:Camera started
INFO:donkeycar.parts.camera:PiCamera opened...
INFO:donkeycar.parts.camera:...warming camera
INFO:donkeycar.parts.camera:PiCamera ready.
INFO:donkeycar.vehicle:Adding part PiCamera.
INFO:donkeycar.parts.web_controller.web:Starting Donkey Server...
INFO:donkeycar.parts.web_controller.web:You can now go to backseat.local:8887 to drive your car.
INFO:donkeycar.vehicle:Adding part LocalWebController.
INFO:donkeycar.vehicle:Adding part Pipe.
INFO:donkeycar.vehicle:Adding part ExplodeDict.
INFO:donkeycar.vehicle:Adding part Lambda.
INFO:donkeycar.vehicle:Adding part Lambda.
INFO:donkeycar.vehicle:Adding part Lambda.
INFO:donkeycar.vehicle:Adding part Lambda.
INFO:donkeycar.vehicle:Adding part Lambda.
INFO:donkeycar.vehicle:Adding part ThrottleFilter.
INFO:donkeycar.vehicle:Adding part UserPilotCondition.
INFO:donkeycar.vehicle:Adding part RecordTracker.
INFO:donkeycar.utils:get_model_by_type: model type is: linear
INFO:donkeycar.parts.keras:Created KerasLinear with interpreter: KerasInterpreter
loading model /home/donkey/mycar/models/pilot_24-10-17_0.savedmodel
INFO:donkeycar.parts.keras:Loading model /home/donkey/mycar/models/pilot_24-10-17_0.savedmodel
INFO:donkeycar.parts.interpreter:Loading model /home/donkey/mycar/models/pilot_24-10-17_0.savedmodel
finished loading in 0.9478845596313477 sec.
INFO:donkeycar.vehicle:Adding part FileWatcher.
INFO:donkeycar.vehicle:Adding part FileWatcher.
INFO:donkeycar.vehicle:Adding part DelayedTrigger.
INFO:donkeycar.vehicle:Adding part TriggeredCallback.
Adding inference transformations
INFO:__main__:Adding inference transformations
INFO:donkeycar.parts.image_transformations:Creating ImageTransformations []
INFO:donkeycar.vehicle:Adding part ImageTransformations.
INFO:donkeycar.vehicle:Adding part KerasLinear.
INFO:donkeycar.vehicle:Adding part AiLaunch.
INFO:donkeycar.vehicle:Adding part DriveMode.
INFO:donkeycar.vehicle:Adding part ToggleRecording.
INFO:donkeycar.parts.actuator:PWM Steering created
INFO:donkeycar.parts.actuator:Init ESC
INFO:donkeycar.parts.actuator:PWM Throttle created
INFO:donkeycar.vehicle:Adding part PWMSteering.
INFO:donkeycar.vehicle:Adding part PWMThrottle.
INFO:donkeycar.parts.datastore_v2:Found datastore at /home/donkey/mycar/data
INFO:donkeycar.parts.datastore_v2:Using last catalog /home/donkey/mycar/data/catalog_14.catalog
INFO:donkeycar.vehicle:Adding part TubWriter.
You can now go to <your hostname.local>:8887 to drive your car.
You can now move your controller to drive your car.
INFO:donkeycar.vehicle:Starting vehicle at 20 Hz
Traceback (most recent call last):
  File "/home/donkey/env/lib/python3.11/site-packages/donkeycar/vehicle.py", line 155, in start
    self.update_parts()
  File "/home/donkey/env/lib/python3.11/site-packages/donkeycar/vehicle.py", line 209, in update_parts
    outputs = p.run(*inputs)
              ^^^^^^^^^^^^^^
  File "/home/donkey/env/lib/python3.11/site-packages/donkeycar/parts/keras.py", line 116, in run
    return self.inference_from_dict(input_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/donkey/env/lib/python3.11/site-packages/donkeycar/parts/keras.py", line 124, in inference_from_dict
    output = self.interpreter.predict_from_dict(input_dict)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/donkey/env/lib/python3.11/site-packages/donkeycar/parts/interpreter.py", line 163, in predict_from_dict
    outputs = self.model(input_dict, training=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/donkey/env/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/donkey/env/lib/python3.11/site-packages/keras/src/engine/input_spec.py", line 298, in assert_input_compatibility
    raise ValueError(
ValueError: Input 0 of layer "linear" is incompatible with the layer: expected shape=(None, 120, 160, 3), found shape=(1, 120, 128, 3)
INFO:donkeycar.vehicle:Shutting down vehicle and its parts...
INFO:donkeycar.parts.camera:Stopping PiCamera
INFO:picamera2.picamera2:Camera stopped
INFO:picamera2.picamera2:Camera closed successfully.
INFO:donkeycar.parts.tub_v2:Closing tub /home/donkey/mycar/data
INFO:donkeycar.parts.datastore_v2:Closing manifest /home/donkey/mycar/data
INFO:donkeycar.vehicle:Part Profile Summary: (times in ms)
INFO:donkeycar.vehicle:
+------+-----+-----+-----+-----+-----+-----+-------+
| part | max | min | avg | 50% | 90% | 99% | 99.9% |
+------+-----+-----+-----+-----+-----+-----+-------+
+------+-----+-----+-----+-----+-----+-----+-------+
```

And the .tflite model produces the following error:

```
(env) donkey@backseat:~/mycar $ python manage.py drive --model ~/mycar/models/pilot_24-10-17_0.tflite --myconfig myconfig.py --type tflite_linear
________             ______                   _________
___  __ \_______________  /___________  __    __  ____/_____ ________
__  / / /  __ \_  __ \_  //_/  _ \_  / / /    _  /    _  __ `/_  ___/
_  /_/ // /_/ /  / / /  ,<  /  __/  /_/ /     / /___  / /_/ /_  /
/_____/ \____//_/ /_//_/|_| \___/_\__, /      \____/  \__,_/ /_/
                                 /____/

using donkey v5.1.0 ...
INFO:donkeycar.config:loading config file: /home/donkey/mycar/config.py
INFO:donkeycar.config:loading personal config over-rides from myconfig.py
INFO:__main__:PID: 2149
cfg.CAMERA_TYPE PICAM
INFO:__main__:cfg.CAMERA_TYPE PICAM
[0:07:45.574593072] [2149]  INFO Camera camera_manager.cpp:325 libcamera v0.3.2+27-7330f29b
[0:07:45.582140306] [2152]  INFO RPI pisp.cpp:695 libpisp version v1.0.7 28196ed6edcf 29-08-2024 (16:33:32)
[0:07:45.591667266] [2152]  INFO RPI pisp.cpp:1154 Registered camera /base/axi/pcie@120000/rp1/i2c@88000/ov5647@36 to CFE device /dev/media0 and ISP device /dev/media2 using PiSP variant BCM2712_C0
[0:07:45.592922120] [2149]  INFO Camera camera_manager.cpp:325 libcamera v0.3.2+27-7330f29b
[0:07:45.600254705] [2155]  INFO RPI pisp.cpp:695 libpisp version v1.0.7 28196ed6edcf 29-08-2024 (16:33:32)
[0:07:45.609871850] [2155]  INFO RPI pisp.cpp:1154 Registered camera /base/axi/pcie@120000/rp1/i2c@88000/ov5647@36 to CFE device /dev/media0 and ISP device /dev/media2 using PiSP variant BCM2712_C0
INFO:picamera2.picamera2:Initialization successful.
INFO:picamera2.picamera2:Camera now open.
INFO:picamera2.picamera2:Camera configuration has been adjusted!
[0:07:45.613163170] [2149]  INFO Camera camera.cpp:1197 configuring streams: (0) 128x120-BGR888 (1) 640x480-GBRG_PISP_COMP1
[0:07:45.613268263] [2155]  INFO RPI pisp.cpp:1450 Sensor: /base/axi/pcie@120000/rp1/i2c@88000/ov5647@36 - Selected sensor format: 640x480-SGBRG10_1X10 - Selected CFE format: 640x480-PC1g
INFO:picamera2.picamera2:Configuration successful!
INFO:picamera2.picamera2:Camera started
INFO:donkeycar.parts.camera:PiCamera opened...
INFO:donkeycar.parts.camera:...warming camera
INFO:donkeycar.parts.camera:PiCamera ready.
INFO:donkeycar.vehicle:Adding part PiCamera.
INFO:donkeycar.parts.web_controller.web:Starting Donkey Server...
INFO:donkeycar.parts.web_controller.web:You can now go to backseat.local:8887 to drive your car.
INFO:donkeycar.vehicle:Adding part LocalWebController.
INFO:donkeycar.vehicle:Adding part Pipe.
INFO:donkeycar.vehicle:Adding part ExplodeDict.
INFO:donkeycar.vehicle:Adding part Lambda.
INFO:donkeycar.vehicle:Adding part Lambda.
INFO:donkeycar.vehicle:Adding part Lambda.
INFO:donkeycar.vehicle:Adding part Lambda.
INFO:donkeycar.vehicle:Adding part Lambda.
INFO:donkeycar.vehicle:Adding part ThrottleFilter.
INFO:donkeycar.vehicle:Adding part UserPilotCondition.
INFO:donkeycar.vehicle:Adding part RecordTracker.
INFO:donkeycar.utils:get_model_by_type: model type is: tflite_linear
INFO:donkeycar.parts.keras:Created KerasLinear with interpreter: TfLite
loading model /home/donkey/mycar/models/pilot_24-10-17_0.tflite
INFO:donkeycar.parts.keras:Loading model /home/donkey/mycar/models/pilot_24-10-17_0.tflite
INFO:donkeycar.parts.interpreter:Loading model /home/donkey/mycar/models/pilot_24-10-17_0.tflite
finished loading in 0.0006306171417236328 sec.
INFO:donkeycar.vehicle:Adding part FileWatcher.
INFO:donkeycar.vehicle:Adding part FileWatcher.
INFO:donkeycar.vehicle:Adding part DelayedTrigger.
INFO:donkeycar.vehicle:Adding part TriggeredCallback.
Adding inference transformations
INFO:__main__:Adding inference transformations
INFO:donkeycar.parts.image_transformations:Creating ImageTransformations []
INFO:donkeycar.vehicle:Adding part ImageTransformations.
INFO:donkeycar.vehicle:Adding part KerasLinear.
INFO:donkeycar.vehicle:Adding part AiLaunch.
INFO:donkeycar.vehicle:Adding part DriveMode.
INFO:donkeycar.vehicle:Adding part ToggleRecording.
INFO:donkeycar.parts.actuator:PWM Steering created
INFO:donkeycar.parts.actuator:Init ESC
INFO:donkeycar.parts.actuator:PWM Throttle created
INFO:donkeycar.vehicle:Adding part PWMSteering.
INFO:donkeycar.vehicle:Adding part PWMThrottle.
INFO:donkeycar.parts.datastore_v2:Found datastore at /home/donkey/mycar/data
INFO:donkeycar.parts.datastore_v2:Using last catalog /home/donkey/mycar/data/catalog_14.catalog
INFO:donkeycar.vehicle:Adding part TubWriter.
You can now go to <your hostname.local>:8887 to drive your car.
You can now move your controller to drive your car.
INFO:donkeycar.vehicle:Starting vehicle at 20 Hz
Traceback (most recent call last):
  File "/home/donkey/env/lib/python3.11/site-packages/donkeycar/vehicle.py", line 155, in start
    self.update_parts()
  File "/home/donkey/env/lib/python3.11/site-packages/donkeycar/vehicle.py", line 209, in update_parts
    outputs = p.run(*inputs)
              ^^^^^^^^^^^^^^
  File "/home/donkey/env/lib/python3.11/site-packages/donkeycar/parts/keras.py", line 116, in run
    return self.inference_from_dict(input_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/donkey/env/lib/python3.11/site-packages/donkeycar/parts/keras.py", line 124, in inference_from_dict
    output = self.interpreter.predict_from_dict(input_dict)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/donkey/env/lib/python3.11/site-packages/donkeycar/parts/interpreter.py", line 278, in predict_from_dict
    outputs = self.runner(**input_dict)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/donkey/env/lib/python3.11/site-packages/tensorflow/lite/python/interpreter.py", line 243, in __call__
    self._interpreter_wrapper.AllocateTensors(self._subgraph_index)
RuntimeError: tensorflow/lite/kernels/reshape.cc:92 num_input_elements != num_output_elements (4608 != 0)Node number 5 (RESHAPE) failed to prepare.
INFO:donkeycar.vehicle:Shutting down vehicle and its parts...
INFO:donkeycar.parts.camera:Stopping PiCamera
INFO:picamera2.picamera2:Camera stopped
INFO:picamera2.picamera2:Camera closed successfully.
INFO:donkeycar.parts.tub_v2:Closing tub /home/donkey/mycar/data
INFO:donkeycar.parts.datastore_v2:Closing manifest /home/donkey/mycar/data
INFO:donkeycar.vehicle:Part Profile Summary: (times in ms)
INFO:donkeycar.vehicle:
+------+-----+-----+-----+-----+-----+-----+-------+
| part | max | min | avg | 50% | 90% | 99% | 99.9% |
+------+-----+-----+-----+-----+-----+-----+-------+
+------+-----+-----+-----+-----+-----+-----+-------+
```

The myconfig.py file has the pilot mode set to local.

**Comment by LuckyYoon** [comment]
FIXED: The Picam was recording in 120 x 128 despite myconfig.py specifying 120 x 160. Thus, the model was trained with the wrong input size. I couldn't figure out a way to get my camera to record in 120 x 160, so I trained a new model with an input size of (None, 120, 128, 3) by changing the IMAGE_W and IMAGE_H in myconfig.py to 128 and 120. Now, the model works with the new size but I'm still not sure why my camera is stuck in this resolution.
