### ISSUE TITLE
Error while running trained model

### ISSUE THREAD

**Issue by rychitre** [autorope/donkeycar#355]
I created model on my computer and transfer to Rpi. When I run command ‘python manage.py drive --model ~/mycar/models/mypilot’ , I get below error.  Any help to resolve the error?

(env) pi@donkeypi:~/mycar $ python manage.py drive --model ~/mycar/models/mypilot
using donkey v2.5.1 ...
/usr/lib/python3/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
loading config file: /home/pi/mycar/config.py
config loaded
PiCamera loaded.. .warming camera
Starting Donkey Server...
Traceback (most recent call last):
  File "manage.py", line 190, in <module>
    drive(cfg, model_path = args['--model'], use_joystick=args['--js'], use_chaos=args['--chaos'])
  File "manage.py", line 78, in drive
    kl.load(model_path)
  File "/home/pi/env/lib/python3.5/site-packages/donkeycar/parts/keras.py", line 21, in load
    self.model = load_model(model_path)
  File "/home/pi/env/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/engine/saving.py", line 241, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/pi/env/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/engine/saving.py", line 318, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/pi/env/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/layers/serialization.py", line 63, in deserialize
    printable_module_name='layer')
  File "/home/pi/env/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/utils/generic_utils.py", line 171, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/pi/env/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/engine/network.py", line 1057, in from_config
    process_layer(layer_data)
  File "/home/pi/env/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/engine/network.py", line 1043, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/home/pi/env/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/layers/serialization.py", line 63, in deserialize
    printable_module_name='layer')
  File "/home/pi/env/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/utils/generic_utils.py", line 173, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/home/pi/env/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/engine/base_layer.py", line 559, in from_config
    return cls(**config)
  File "/home/pi/env/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/layers/convolutional.py", line 261, in __init__
    kernel_initializer=initializers.get(kernel_initializer),
  File "/home/pi/env/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/initializers.py", line 205, in get
    return deserialize(identifier)
  File "/home/pi/env/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/initializers.py", line 199, in deserialize
    printable_module_name='initializer')
  File "/home/pi/env/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/utils/generic_utils.py", line 161, in deserialize_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown initializer: GlorotUniform

**Comment by yishuifengxing** [comment]
I have the same problem. I don't know how to solve it.
