### ISSUE TITLE
donkey car create error

### ISSUE THREAD

**Issue by balakreshnan** [autorope/donkeycar#710]
Try to update the code and create donkey car and it is giving me error

remote: Total 16 (delta 6), reused 9 (delta 6), pack-reused 0
Unpacking objects: 100% (16/16), done.
From https://github.com/autorope/donkeycar
   8940db2..1e6d8a3  master     -> origin/master
   ff35d5f..5ae45b8  dev        -> origin/dev
Updating 8940db2..1e6d8a3
Fast-forward
 docs/dev_guide/model.md | 324 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 docs/utility/donkey.md  |  10 +++
 mkdocs.yml              |   2 +
 3 files changed, 336 insertions(+)
 create mode 100644 docs/dev_guide/model.md
(env) pi@autocar:~/projects/donkeycar $ donkey createcar --path ~/mycar --overwrite
using donkey v3.1.5 ...
Traceback (most recent call last):
  File "/home/pi/env/bin/donkey", line 11, in <module>
    load_entry_point('donkeycar', 'console_scripts', 'donkey')()
  File "/home/pi/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/pi/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/home/pi/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/pi/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pi/projects/donkeycar/donkeycar/management/base.py", line 15, in <module>
    from donkeycar.management.joystick_creator import CreateJoystick
  File "/home/pi/projects/donkeycar/donkeycar/management/joystick_creator.py", line 10, in <module>
    from donkeycar.parts.controller import JoystickCreatorController
  File "/home/pi/projects/donkeycar/donkeycar/parts/controller.py", line 13, in <module>
    from donkeycar.parts.web_controller.web import LocalWebController
  File "/home/pi/projects/donkeycar/donkeycar/parts/web_controller/web.py", line 240
    print(f"wsCalibrate {message}")

**Comment by DocGarbanzo** [comment]
Please upgrade your Pi - I can see you are on python 3.5, you need at least >= 3.6, which you get w/ buster.
