### ISSUE TITLE
Error when running python manage.py drive

### ISSUE THREAD

**Issue by kelvham** [autorope/donkeycar#738]
Hey all, I have made it to the fine-tuning for calibration for the Donkey car setup where you first run `python manage.py drive`, however, when I run it, I get this error.

(env) pi@raspberrypi:~/mycar$ python manage.py drive
________             ______                   _________              
___  __ \_______________  /___________  __    __  ____/_____ ________
__  / / /  __ \_  __ \_  //_/  _ \_  / / /    _  /    _  __ `/_  ___/
_  /_/ // /_/ /  / / /  ,<  /  __/  /_/ /     / /___  / /_/ /_  /    
/_____/ \____//_/ /_//_/|_| \___/_\__, /      \____/  \__,_/ /_/     
                                 /____/                              

using donkey v4.1.0 ...
loading config file: /home/pi/mycar/config.py
loading personal config over-rides from myconfig.py
PiCamera loaded.. .warming camera
Adding part PiCamera.
Starting Donkey Server...... you can now go to raspberrypi.local:8887 to drive your car.
Adding part LocalWebController.
Adding part PilotCondition.
Adding part DriveMode.
Traceback (most recent call last):
  File "manage.py", line 171, in <module>
    drive(cfg, model_path=args['--model'], model_type=args['--type'])
  File "manage.py", line 136, in drive
    if cfg.DONKEY_GYM or cfg.DRIVE_TRAIN_TYPE == "MOCK":
AttributeError: 'Config' object has no attribute 'DRIVE_TRAIN_TYPE'

**Comment by kelvham** [comment]
`(env) pi@raspberrypi:~/mycar$ python manage.py drive
________             ______                   _________              
___  __ \_______________  /___________  __    __  ____/_____ ________
__  / / /  __ \_  __ \_  //_/  _ \_  / / /    _  /    _  __ `/_  ___/
_  /_/ // /_/ /  / / /  ,<  /  __/  /_/ /     / /___  / /_/ /_  /    
/_____/ \____//_/ /_//_/|_| \___/_\__, /      \____/  \__,_/ /_/     
                                 /____/                              

using donkey v4.1.0 ...
loading config file: /home/pi/mycar/config.py
loading personal config over-rides from myconfig.py
PiCamera loaded.. .warming camera
Adding part PiCamera.
Starting Donkey Server...... you can now go to raspberrypi.local:8887 to drive your car.
Adding part LocalWebController.
Adding part PilotCondition.
Adding part DriveMode.
Traceback (most recent call last):
  File "manage.py", line 171, in <module>
    drive(cfg, model_path=args['--model'], model_type=args['--type'])
  File "manage.py", line 136, in drive
    if cfg.DONKEY_GYM or cfg.DRIVE_TRAIN_TYPE == "MOCK":
AttributeError: 'Config' object has no attribute 'DRIVE_TRAIN_TYPE'
`

**Comment by kelvham** [comment]
Managed to fix this issue, applied this method https://github.com/autorope/donkeycar/pull/725/files/fc6906f6dbdd0812d5c9cc8b32222a5987a4797c to the config.py file.
