### ISSUE TITLE
Error while running createcar in donkey setup.

### ISSUE THREAD

**Issue by Endetrix** [autorope/donkeycar#778]
Terminal as below :

(env) pi@donkeypi :~ $ donkey createcar --path ~/mycar

Traceback (most recent call last):
  File "/home/pi/env/bin/donkey", line 33, in <module>
    sys.exit(load_entry_point('donkeycar', 'console_scripts', 'donkey')())
  File "/home/pi/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/pi/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/home/pi/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/pi/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pi/projects/donkeycar/donkeycar/__init__.py", line 8
    print(f'using donkey v{__version__} ...')
                                           ^
SyntaxError: invalid syntax

Any and all help/advice is appreciated :D

**Comment by sctse999** [comment]
python 3.5 is not supported.
