### ISSUE TITLE
dev branch reinstall on Mac fails

### ISSUE THREAD

**Issue by Ezward** [autorope/donkeycar#993]
I'm trying to reinstall on my Macbook Air (i5, so x86, not ARM) and did the steps to remove the conda donkey environment as per https://docs.donkeycar.com/guide/host_pc/setup_mac/
```
conda update -n base -c defaults conda
conda env remove -n donkey
```
Then tried to recreate the environment, but this fails;

```
[15:17:10] (base) Eds-MacBook-Air:donkeycar edmurphy$ conda env create -f install/envs/mac.yml
Collecting package metadata (repodata.json): failed
WARNING conda.exceptions:print_unexpected_error_report(1214): KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1080, in __call__
    return func(*args, **kwargs)
  File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 141, in execute
    result[installer_type] = installer.install(prefix, pkg_specs, args, env)
  File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda_env/installers/conda.py", line 51, in install
    prune=getattr(args, 'prune', False), update_modifier=UpdateModifier.FREEZE_INSTALLED)
  File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 262, in solve_final_state
    ssc = self._collect_all_metadata(ssc)
  File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 397, in _collect_all_metadata
    _supplement_index_with_system(virtual_pkg_index)
  File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 159, in _supplement_index_with_system
    cuda_version = context.cuda_version
  File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/auxlib/decorators.py", line 268, in new_fget
    cache[inner_attname] = func(self)
  File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 20, in wrapper
    return func(*args, **kwargs)
  File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 850, in cuda_version
    return cuda_detect()
  File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
    import ctypes
  File "/Users/edmurphy/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/Users/edmurphy/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /Users/edmurphy/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1212, in print_unexpected_error_report
    message_builder.append(get_main_info_str(error_report['conda_info']))
  File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 237, in get_main_info_str
    info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 141, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda_env/installers/conda.py", line 51, in install
        prune=getattr(args, 'prune', False), update_modifier=UpdateModifier.FREEZE_INSTALLED)
      File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 397, in _collect_all_metadata
        _supplement_index_with_system(virtual_pkg_index)
      File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 159, in _supplement_index_with_system
        cuda_version = context.cuda_version
      File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/auxlib/decorators.py", line 268, in new_fget
        cache[inner_attname] = func(self)
      File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 20, in wrapper
        return func(*args, **kwargs)
      File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 850, in cuda_version
        return cuda_detect()
      File "/Users/edmurphy/miniconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
        import ctypes
      File "/Users/edmurphy/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen(/Users/edmurphy/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
      Referenced from: /Users/edmurphy/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
      Reason: image not found

`$ /Users/edmurphy/miniconda3/bin/conda-env create -f install/envs/mac.yml`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')
```

**Comment by DocGarbanzo** [comment]
Looks like your miniconda base environment is somehow messed up. Can you re-install that? I would also recommend to run 
```bash
conda install mamba
mamba env create -f install/envs/mac.yml
```
Because the env resolution in conda currently takes ages.
